### ISSUE TITLE
Enum parsing

### ISSUE THREAD

**Issue by markcohen32** [SystemRDL/systemrdl-compiler#130]
Hi,

I've been trying recently to import ipxact files that contain enums. I get the following error:
"_names_ are reserved for future Enum use"
I've tried Python 3.6 & Python 3.9. Is it an issue related to the importer?

**Comment by markcohen32** [comment]
Hi, is there an update regarding this bug?

**Comment by amykyta3** [comment]
Was on vacation. Will look into it more now that I am back

**Comment by markcohen32** [comment]
Hi, any new? :)

**Comment by amykyta3** [comment]
I have a plan on how to fix this, but it is more intrusive than I had hoped.
The plan is to migrate away from the use of Python's `Enum` objects to represent user-defined enumerations. This would address this issue, as well as other quirks that result from this (inability to pickle register models). Instead of `Enum` classes, RDL enumerated types would be represented by more specialized class instances. A similar change would be done for RDL struct representations, but i expect they are less often used.

The biggest challenge is that I need to build a migration path that is not intrusive to the community and do my best to not break compatibility with current usages. I have a general plan for this, but still need to think through some details.

**Comment by amykyta3** [comment]
See planned rework details in #132.
I hope to get this fixed in the next few weeks.

**Comment by amykyta3** [comment]
Fixed in v1.24.0
