### ISSUE TITLE
detecting name collisions during path serialization

### ISSUE THREAD

**Issue by jeras** [SystemRDL/systemrdl-compiler#193]
The feature I would like to see, is testing for whether there are serialized name collisions.
This collisions can occur when the when one hierarchy contains an instance named `foo_bar` and also a sub hierarchy named `foo` and containing instance `bar`. When using `get_path(hier_separator='_')`  both of the above branches would result in `foo_bar` thus causing a name collision.

`test.rdl` file
```SystemRDL
addrmap test {
    default accesswidth = 32;
    regfile {
       reg {
           field {
           } val [32];
       } value;
    } conf;
    reg {
        field {
        } val [16];
    } conf__value;
};
```

```sh
peakrdl c-header test.rdl -o test
```

Since the latest version of PeakRDL-cheader is using a double underscore `__` as a separator, I used the same in the example.
The generator will create a single field definition instead of two separate definitions due to a name collision.

I think there should be a way to detect such collisions.
It might be a global check for the given separator, or a check should be done each time `get_path(hier_separator='_')` is called.

**Comment by amykyta3** [comment]
I agree that exporters should check for such collisions.
Since this is specific to how each unique exporter will generate its content, and not something that would be appropriate for the systemrdl-compiler project to enforce, I will close this issue. I have created enhancement issue tickets in the three projects I own that are susceptible for such a collision and will fix individually.
