### ISSUE TITLE
Obtaining the line number

### ISSUE THREAD

**Issue by kjeldbeg** [SystemRDL/systemrdl-compiler#85]
If I discover a problem with a node (e.g. a property is not set) I would like to generate an error message with the line number from the RDL file. Is that information available?

**Comment by amykyta3** [comment]
Since you simply want to print messages to the user, I recommend using the existing message handler. This will print messages in a format that is consistent with the rest of the compiler, and also include source context. I assume this will do what you need implicitly.

Here is an example that uses the [atxmega_spi.rdl](https://github.com/SystemRDL/systemrdl-compiler/blob/master/examples/atxmega_spi.rdl#L64-L66) demo file:
```python
from systemrdl import RDLCompiler
rdlc = RDLCompiler()
rdlc.compile_file("atxmega_spi.rdl")
root = rdlc.elaborate()

# Print messages without any context
rdlc.msg.warning("Warning Message")
rdlc.msg.error("Error Message")

# Print messages with source context
data_if_field = root.top.find_by_path("STATUS.IF")
rdlc.msg.warning(
    "Field definition is here",
    data_if_field.inst.def_src_ref
)
rdlc.msg.warning(
    "Field instance is here",
    data_if_field.inst.inst_src_ref
)
rdlc.msg.warning(
    "Assignment of the 'hw' property is here",
    data_if_field.inst.property_src_ref['hw']
)
```
Running the above script produces this output:
![image](https://user-images.githubusercontent.com/12021539/118072728-52f53a00-b35f-11eb-9556-44434377fc5f.png)

I'll add the `RDLCompiler.msg` attribute to the documentation. That really ought to be part of the public API.

**Comment by amykyta3** [comment]
Updated docs:
* https://systemrdl-compiler.readthedocs.io/en/latest/api/compiler.html#systemrdl.RDLCompiler.msg
* https://systemrdl-compiler.readthedocs.io/en/latest/api/messages.html#systemrdl.messages.MessageHandler
* https://systemrdl-compiler.readthedocs.io/en/latest/api/component.html#systemrdl.component.Component.inst_src_ref

**Comment by kjeldbeg** [comment]
Just what I needed. Thank you very much.
